name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
      
    # 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: my-artifact
        path: /home/runner/work/RESTAURANT/RESTAURANT/  # or path/to/artifact
        
    #  
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.tag_name }}
    
    #
    - name: Install deps and build
      run: npm ci && npm run build
    - uses: JasonEtco/build-and-tag-action@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}

  
      
